name: Update Yaml files

on:
  pull_request:
  push:
    branches:    
    - '**'
    - '!main'

jobs:
  psalm:
    name: update yaml files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: update yaml files
        run: |
          sudo bash manual-install/update-yaml.sh
      - name: Commit files
        if: ${{ success() }}
        continue-on-error: true
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update Yaml files" -a
      - name: Push changes
        if: ${{ success() }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
